import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Game} from '../dist/engine.mjs';
import {CARDS,BY_ID,deck} from '../dist/cards.mjs';
const id=name=>CARDS.find(c=>c.name===name).id;
function setup(){const g=new Game();g.players.forEach(p=>Object.assign(p,{hand:[],field:[],grave:[],life:20}));g.phase='main1';return g;}
function add(g,p,name,zone='field'){const c=g.card(id(name));g.players[p][zone].push(c);return c;}
function mana(g,p,n=10){for(let i=0;i<n;i++)add(g,p,p===0?'Secure Datacenter':'Relay Node');}
function resolve(g){g.pass(g.priority);g.pass(g.priority);}
test('50 illustrated cards; each faction has a legal 60-card starter',()=>{assert.equal(CARDS.length,50);for(const f of ['red','blue']){assert.equal(deck(f).length,60);assert.equal(CARDS.filter(c=>c.faction===f).length,25);}for(const c of CARDS)assert.ok(fs.existsSync(new URL(`../dist/art/${c.art}.webp`,import.meta.url)));});
test('London mulligan bottoms chosen cards and skips first draw',()=>{const g=new Game();g.mulligan();assert.equal(g.players[0].hand.length,7);const bottom=g.players[0].hand[0];assert.throws(()=>g.keep([]));g.keep([bottom.uid]);assert.equal(g.players[0].hand.length,6);assert.equal(g.players[0].deck[0].uid,bottom.uid);resolve(g);resolve(g);assert.equal(g.phase,'main1');assert.equal(g.players[0].hand.length,6);});
test('one land per turn, exact payment, main-phase timing',()=>{const g=setup();const l=add(g,0,'Secure Datacenter','hand'),l2=add(g,0,'Secure Datacenter','hand'),u=add(g,0,'SOC Trainee','hand');g.play(0,l.uid);assert.equal(g.mana(0),1);assert.equal(g.legal(0,l2),false);g.play(0,u.uid);assert.equal(g.mana(0),0);assert.equal(g.stack.length,1);resolve(g);assert.equal(g.players[0].field.length,2);g.priority=1;assert.equal(g.legal(0,l2),false);});
test('last-in first-out and counterspells',()=>{const g=setup();mana(g,0);mana(g,1);const draw=add(g,0,'Correlate Logs','hand'),counter=add(g,1,'Disrupt Telemetry','hand');g.play(0,draw.uid);g.pass(0);g.play(1,counter.uid,{kind:'spell',uid:draw.uid});resolve(g);assert.equal(g.stack.length,0);assert.ok(g.players[0].grave.includes(draw));assert.ok(g.players[1].grave.includes(counter));});
test('counter may target a lower spell without affecting top spell',()=>{const g=setup();mana(g,0);mana(g,1);const draw=add(g,0,'Correlate Logs','hand'),heal=add(g,0,'Restore Backup','hand'),counter=add(g,1,'Disrupt Telemetry','hand');g.play(0,draw.uid);g.play(0,heal.uid);g.pass(0);g.play(1,counter.uid,{kind:'spell',uid:draw.uid});resolve(g);assert.equal(g.stack.length,1);assert.equal(g.stack[0].card.id,heal.id);resolve(g);assert.equal(g.players[0].life,24);});
test('new arrivals, rapid deploy, always-on, firewall, stealth and detection',()=>{const g=setup();const plain=add(g,0,'Incident Responder'),haste=add(g,0,'Threat Hunter'),wall=add(g,0,'Segmentation Gateway'),fly=add(g,1,'Rogue Access Point'),ground=add(g,0,'SOC Trainee');assert.equal(g.canAttack(0,plain),false);assert.equal(g.canAttack(0,haste),true);wall.sick=false;assert.equal(g.canAttack(0,wall),false);assert.equal(g.canBlock(ground,fly),false);assert.equal(g.canBlock(wall,fly),true);plain.sick=false;g.phase='attack';g.attackers(0,[plain.uid]);assert.equal(plain.tapped,false);});
test('simultaneous damage destroys both units and recharge gains capacity',()=>{const g=setup(),a=add(g,0,'Awareness Champion'),b=add(g,1,'Payload Runner');a.sick=false;g.phase='attack';g.attackers(0,[a.uid]);g.phase='block';g.blockers(1,{[a.uid]:[b.uid]});g.combat();assert.equal(g.players[0].life,22);assert.ok(g.players[0].grave.includes(a));assert.ok(g.players[1].grave.includes(b));assert.equal(g.players[1].life,20);});
test('overflow assigns lethal damage then spills through',()=>{const g=setup(),a=add(g,0,'Resilience Architect'),b=add(g,1,'Recon Operator');a.sick=false;g.phase='attack';g.attackers(0,[a.uid]);g.phase='block';g.blockers(1,{[a.uid]:[b.uid]});g.combat();assert.equal(g.players[1].life,17);assert.equal(a.damage,1);});
test('multiple blockers, no repeated blockers, and blocked status persists',()=>{const g=setup(),a=add(g,0,'Incident Responder'),b=add(g,1,'Recon Operator'),b2=add(g,1,'Recon Operator');a.sick=false;g.phase='attack';g.attackers(0,[a.uid]);g.phase='block';assert.throws(()=>g.blockers(1,{[a.uid]:[b.uid,b.uid]}));g.blockers(1,{[a.uid]:[b.uid,b2.uid]});g.remove(1,b);g.remove(1,b2);g.combat();assert.equal(g.players[1].life,20);});
test('invalid target fizzles after bounce and zone changes create new objects',()=>{const g=setup();mana(g,0);mana(g,1);const unit=add(g,1,'Payload Runner'),damage=add(g,0,'Emergency Patch','hand'),bounce=add(g,1,'Token Replay','hand'),old=unit.uid;g.play(0,damage.uid,{kind:'card',uid:old});g.pass(0);g.play(1,bounce.uid,{kind:'card',uid:old});resolve(g);assert.notEqual(unit.uid,old);resolve(g);assert.ok(g.players[1].hand.includes(unit));assert.equal(g.stack.length,0);assert.match(g.log[0],/no legal target/);});
test('MFA prevents phishing but not other sources',()=>{const g=setup();add(g,0,'Phishing-Resistant MFA');const phish=add(g,1,'Credential Phishing','hand'),dos=add(g,1,'Denial of Service','hand');mana(g,1);g.active=g.priority=1;g.play(1,phish.uid,{kind:'player',p:0});resolve(g);assert.equal(g.players[0].life,20);g.play(1,dos.uid,{kind:'player',p:0});resolve(g);assert.equal(g.players[0].life,16);});
test('destroy, draw, heal, buff, recover, anthem and upkeep effects',()=>{const g=setup();mana(g,0,20);const u=add(g,0,'SOC Trainee');const buff=add(g,0,'Privilege Escalation','hand');g.play(0,buff.uid,{kind:'card',uid:u.uid});resolve(g);assert.deepEqual(g.stats(u,0),{power:4,toughness:3});const destroy=add(g,0,'Isolate Host','hand');g.play(0,destroy.uid,{kind:'card',uid:u.uid});resolve(g);const recover=add(g,0,'Clean Rebuild','hand');g.play(0,recover.uid,{kind:'card',uid:u.uid});resolve(g);assert.ok(g.players[0].hand.includes(u));assert.equal(u.bp,0);const before=g.players[0].hand.length;const draw=add(g,0,'Correlate Logs','hand');g.play(0,draw.uid);resolve(g);assert.equal(g.players[0].hand.length,before+2);add(g,0,'Command Channel');const u2=add(g,0,'SOC Trainee');assert.equal(g.stats(u2,0).power,2);add(g,1,'Botnet Reserve');g.endTurn();assert.equal(g.players[1].life,21);});
test('cleanup removes marked damage, temporary buffs, and requires discards',()=>{const g=setup(),u=add(g,0,'SOC Trainee');u.damage=1;u.bp=3;for(let i=0;i<9;i++)add(g,0,'Secure Datacenter','hand');g.phase='end';resolve(g);assert.equal(g.phase,'cleanup');assert.throws(()=>g.discard([]));g.discard(g.players[0].hand.slice(0,2).map(c=>c.uid));assert.equal(g.players[0].hand.length,7);assert.equal(u.damage,0);assert.equal(u.bp,0);assert.equal(g.active,1);});
test('empty-deck loss and simultaneous capacity draw',()=>{let g=setup();g.players[0].deck=[];g.draw(0,1);assert.equal(g.winner,1);g=setup();g.players[0].life=g.players[1].life=0;g.check();assert.equal(g.winner,'draw');});
test('100 seeded complete matches preserve card counts and finish without deadlock',()=>{const wins={red:0,blue:0,draw:0};let maxTurns=0;for(let seed=1;seed<=100;seed++){let s=seed;const rng=()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296;};const g=new Game(seed%2?'blue':'red',rng);g.keep();for(let steps=0;steps<10000&&g.winner===null;steps++){if(g.actor()===1){g.aiAction();continue;}if(g.phase==='attack'){g.attackers(0,g.players[0].field.filter(c=>g.canAttack(0,c)).map(c=>c.uid));continue;}if(g.phase==='block'){const assignments={},bs=g.players[0].field.filter(c=>BY_ID[c.id].type==='Unit'&&!c.tapped);for(const uid of g.attacks){const a=g.find(uid);if(!a||a.zone!=='field')continue;const i=bs.findIndex(b=>g.canBlock(b,a.card));if(i>=0)assignments[uid]=[bs.splice(i,1)[0].uid];}g.blockers(0,assignments);continue;}if(g.phase==='cleanup'){g.discard(g.players[0].hand.slice(0,g.players[0].hand.length-7).map(c=>c.uid));continue;}const cs=g.players[0].hand.filter(c=>g.legal(0,c));let played=false;for(const c of cs){const d=BY_ID[c.id];let ts=g.targets(0,c);if(d.target==='unit'||d.target==='support')ts=ts.filter(t=>g.find(t.uid).p===(d.effect==='buff'&&d.powerBoost>0?0:1));if(d.target==='spell')ts=ts.filter(t=>g.stack.find(s=>s.card.uid===t.uid).p===1);if(d.target&&!ts.length)continue;g.play(0,c.uid,ts[0]||null);played=true;break;}if(!played)g.pass(0);}
assert.notEqual(g.winner,null,`seed ${seed} did not finish`);for(let p=0;p<2;p++){const q=g.players[p],total=q.deck.length+q.hand.length+q.field.length+q.grave.length+g.stack.filter(s=>s.p===p).length;assert.equal(total,60,`card conservation seed ${seed}, player ${p}`);}wins[g.winner==='draw'?'draw':g.players[g.winner].faction]++;maxTurns=Math.max(maxTurns,g.turn);}console.log('Simulation diagnostics (different play policies, not a balance benchmark):',wins,'max turns',maxTurns);});
test('blocks must name attackers by canonical uid with a list of blockers',()=>{const g=setup(),a=add(g,0,'Incident Responder'),b=add(g,1,'Recon Operator');a.sick=false;g.phase='attack';g.attackers(0,[a.uid]);g.phase='block';for(const bad of [{[`0${a.uid}`]:[b.uid]},{[`0x${a.uid.toString(16)}`]:[b.uid]},{[` ${a.uid}`]:[b.uid]},{[a.uid]:String(b.uid)},{[a.uid]:''},[]])assert.throws(()=>g.blockers(1,bad));assert.equal(g.phase,'block');g.blockers(1,{[a.uid]:[b.uid]});assert.deepEqual(g.blocks,{[a.uid]:[b.uid]});});
